# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  compose:up:
    desc: "run all docker containers"
    cmd: docker compose up -d
  
  compose:down:
    desc: "stop all docker containers"
    cmd: docker compose down
  
  db:cli:
    desc: "access postgres db cli"
    cmd: docker exec -it postgres psql -U {{ .DB_USER }} -b {{ .DB_NAME }}

  gen:inventory:
    desc: "generate inventory protobuf"
    cmd: protoc --go_out=services/common/genproto/inventory --go_opt=paths=source_relative --go-grpc_out=services/common/genproto/inventory --go-grpc_opt=paths=source_relative protobuf/inventory.proto

  dev:user:
    desc: "run user http services locally"
    cmd: go run services/user-service/cmd/http/main.go

  dev:order:
    desc: "run order http services locally"
    cmd: go run services/order-service/cmd/http/main.go

  dev:inventory:
    desc: "run inventory grpc services locally"
    cmd: go run services/inventory-service/cmd/grpc/main.go
