# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  compose:up:
    desc: "run all docker containers"
    cmd: docker compose up -d
  
  compose:down:
    desc: "stop all docker containers"
    cmd: docker compose down
  
  db:cli:
    desc: "access postgres db cli"
    cmd: docker exec postgres psql -U {{ .DB_USER }} -b {{ .DB_NAME }}

  gen:inventory:
    desc: "generate inventory protobuf"
    cmd: protoc --go_out=services/common/genproto/inventory --go_opt=paths=source_relative --go-grpc_out=services/common/genproto/inventory --go-grpc_opt=paths=source_relative protobuf/inventory.proto
