// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: protobuf/inventory.proto

package inventory

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryReq) Reset() {
	*x = CreateInventoryReq{}
	mi := &file_protobuf_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryReq) ProtoMessage() {}

func (x *CreateInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryReq.ProtoReflect.Descriptor instead.
func (*CreateInventoryReq) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInventoryReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateInventoryReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateInventoryRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryRes) Reset() {
	*x = CreateInventoryRes{}
	mi := &file_protobuf_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryRes) ProtoMessage() {}

func (x *CreateInventoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryRes.ProtoReflect.Descriptor instead.
func (*CreateInventoryRes) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInventoryRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_protobuf_inventory_proto protoreflect.FileDescriptor

const file_protobuf_inventory_proto_rawDesc = "" +
	"\n" +
	"\x18protobuf/inventory.proto\x12\tinventory\"O\n" +
	"\x12CreateInventoryReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\".\n" +
	"\x12CreateInventoryRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2e\n" +
	"\x10InventoryService\x12Q\n" +
	"\x0fCreateInventory\x12\x1d.inventory.CreateInventoryReq\x1a\x1d.inventory.CreateInventoryRes\"\x00BMZKgithub.com/yehezkiel1086/go-grpc-inventory-microservices/protobuf/inventoryb\x06proto3"

var (
	file_protobuf_inventory_proto_rawDescOnce sync.Once
	file_protobuf_inventory_proto_rawDescData []byte
)

func file_protobuf_inventory_proto_rawDescGZIP() []byte {
	file_protobuf_inventory_proto_rawDescOnce.Do(func() {
		file_protobuf_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_inventory_proto_rawDesc), len(file_protobuf_inventory_proto_rawDesc)))
	})
	return file_protobuf_inventory_proto_rawDescData
}

var file_protobuf_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_inventory_proto_goTypes = []any{
	(*CreateInventoryReq)(nil), // 0: inventory.CreateInventoryReq
	(*CreateInventoryRes)(nil), // 1: inventory.CreateInventoryRes
}
var file_protobuf_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.InventoryService.CreateInventory:input_type -> inventory.CreateInventoryReq
	1, // 1: inventory.InventoryService.CreateInventory:output_type -> inventory.CreateInventoryRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_inventory_proto_init() }
func file_protobuf_inventory_proto_init() {
	if File_protobuf_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_inventory_proto_rawDesc), len(file_protobuf_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_inventory_proto_goTypes,
		DependencyIndexes: file_protobuf_inventory_proto_depIdxs,
		MessageInfos:      file_protobuf_inventory_proto_msgTypes,
	}.Build()
	File_protobuf_inventory_proto = out.File
	file_protobuf_inventory_proto_goTypes = nil
	file_protobuf_inventory_proto_depIdxs = nil
}
